src/com/crismasecurity/mediasetStudios/web/LanguageBean.java
package com.crismasecurity.mediasetStudios.web;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;


//@ManagedBean(name= "languageBean") // JSF managed
//@SessionScoped // JSF managed
//@ViewScoped // JSF managed

//Spring managed
@Controller ("languageBean") 
@Scope("session")
//@Scope("view")
public class LanguageBean implements Serializable{

	private static final long serialVersionUID = -7941035963910235077L;

	private String localeCode;
	private Locale currentLocale;

	private static Map<String,Object> countries;
	static{
		countries = new LinkedHashMap<String,Object>();
		countries.put("English", Locale.ENGLISH); //label, value
		countries.put("Italiano", Locale.ITALIAN);
	}

	public LanguageBean() {
		System.out.println("!!!! Costruttore di LanguageBean !!!");
		
    }

	@PostConstruct
	public void init() {
		System.out.println("INIT LanguageBean");
		
		currentLocale = FacesContext.getCurrentInstance().getViewRoot().getLocale();
		
		localeCode = currentLocale.getLanguage();
	}
	
	
	
	public Map<String, Object> getCountriesInMap() {
		return countries;
	}


	public String getLocaleCode() {
		return localeCode;
	}


	public void setLocaleCode(String localeCode) {
		this.localeCode = localeCode;
	}

	//value change event listener
	public void countryLocaleCodeChanged(ValueChangeEvent e){

		String newLocaleValue = e.getNewValue().toString();

		//loop country map to compare the locale code
		for (Map.Entry<String, Object> entry : countries.entrySet()) {
			if(entry.getValue().toString().equals(newLocaleValue)){
				System.out.println("Imposto language: " + newLocaleValue);
        		FacesContext.getCurrentInstance().getViewRoot().setLocale((Locale)entry.getValue());
        		setCurrentLocale((Locale)entry.getValue());
        	  }
		}
	}

	public Locale getCurrentLocale() {
		return currentLocale;
	}

	public void setCurrentLocale(Locale currentLocale) {
		this.currentLocale = currentLocale;
	}

}

WebContent/WEB-INF/templates/baseTemplateSingleRow.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<f:view locale="#{languageBean.currentLocale}">

	<h:head>
		<!-- Mobile a tutto schermo -->
		<meta name="apple-mobile-web-app-capable" content="yes"></meta>
		<meta name="mobile-web-app-capable" content="yes"></meta>
		<!-- <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/> -->
		<!-- <meta name="viewport" content="width=device-width, height=device-height,  initial-scale=1.0, user-scalable=no;user-scalable=0;"/>  -->
		<meta name="viewport"
			content="width=device-width, height=device-height,  initial-scale=0.6, maximum-scale=1.0; minimum-scale=0.5" />

		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>


		<!-- NO CACHE -->
		<meta http-equiv="cache-control" content="max-age=0" />
		<meta http-equiv="cache-control" content="no-cache" />
		<meta http-equiv="expires" content="0" />
		<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
		<meta http-equiv="pragma" content="no-cache" />
		<meta http-equiv="cache-control" content="no-store" />


		<title>MediasetStudios - <ui:insert name="page-title"></ui:insert>
		</title>


		<h:outputStylesheet library="css" name="style.css"></h:outputStylesheet>
		<h:outputStylesheet library="css" name="responsive.css"></h:outputStylesheet>
		<h:outputStylesheet library="css" name="custom.css"></h:outputStylesheet>


		<!-- <h:outputScript library="js" name="jquery.js"></h:outputScript>  -->

		<script type="text/javascript">
        // <![CDATA[ 
                //var myJQuery = jQuery.noConflict();
				//var $ = myJQuery;
				var myJQuery = $;
          // ]]> 
        </script>

		<h:outputScript library="js" name="myScript.js"></h:outputScript>


	</h:head>
	<h:body>
		<p:layout id="layout_elemento" styleClass="" fullPage="true"
			widgetVar="layout_elemento">

			<p:layoutUnit id="layout_elemento_centro"
				styleClass="baseTemplateSingleRowCls" position="center"
				style="border: 0 !important;">
				<ui:insert name="page-menu"></ui:insert>

				<ui:insert name="page-content"></ui:insert>
			</p:layoutUnit>

			<p:layoutUnit position="south" size="30" resizable="false"
				collapsible="false">
				<ui:insert name="footer">
					<ui:include src="/WEB-INF/templates/footer.xhtml" />
				</ui:insert>
			</p:layoutUnit>
		</p:layout>
	</h:body>
</f:view>
</html>

WebContent/WEB-INF/templates/footer.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:sec="http://sourceforge.net/projects/jsf-comp/acegijsf">



	<div
		style="width: 100%; text-align: center; font-size: 12px !important;">MediasetStudios
		-</div>


</ui:composition>

WebContent/WEB-INF/templates/header.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:sec="http://www.springframework.org/security/tags">

	<pe:slideout id="slideoutContact" title="#{msgs['options']}"
		handleOffsetReverse="false" icon="fa fa-envelope" location="right"
		widgetVar="slideout" handleStyleClass="contact-handle"
		panelStyleClass="contact-panel" offset="2px" bounceTimes="5"
		bounceDistance="100px" rendered="#{loginBean.userLoggedIn}">

		<h:form id="form__header_options">
			<h:panelGrid columns="1" id="user_settings">
				<div style="height: 12px; width: 10px;" />
				<h:outputText rendered="#{loginBean.userLoggedIn}"
					value="#{loginBean.userDescription} " />
					
				<div style="height: 12px; width: 10px;" />

				<p:themeSwitcher value="#{styleBean.theme}" label="#{msgs['theme']}"
					id="advanced" style="width: 85%;" effect="fade" var="t">
					<f:selectItem itemLabel="#{msgs['chooseTheme']}" itemValue="" />
					<f:selectItem itemLabel="afterdark" itemValue="afterdark" />
					<f:selectItem itemLabel="aristo" itemValue="aristo" />
					<f:selectItem itemLabel="casablanca" itemValue="casablanca" />
					<f:selectItem itemLabel="cruze" itemValue="cruze" />
					<f:selectItem itemLabel="overcast" itemValue="overcast" />
					<f:selectItem itemLabel="themes-project" itemValue="themes-project" />
					<f:ajax render="@all" />
				</p:themeSwitcher>

				<p:selectOneMenu style="width: 85%;" label="#{msgs['language']}"
					labelPosition="top" value="#{languageBean.localeCode}"
					valueChangeListener="#{languageBean.countryLocaleCodeChanged}">
					<f:selectItems value="#{languageBean.countriesInMap}" />
					<f:ajax render="@all" />
				</p:selectOneMenu>

				<div style="height: 12px; width: 10px;" />

				<h:commandLink style="font-size: 85%;"
					value="#{msgs['change_password']}" action="userSettings">
					<p:ajax update="form_header" />
				</h:commandLink>

				<div style="height: 12px; width: 10px;" />
				<hr style="color: lightgray;" />

				<h:commandLink
					style="font-weight:bold; font-size: 90%;margin-right: 5px;"
					actionListener="#{loginBean.logout}" value="#{msgs['logout']}">
					<p:ajax update="form__header_options" />
				</h:commandLink>
			</h:panelGrid>
		</h:form>
	</pe:slideout>
	<h:form id="form_header" rendered="#{loginBean.userLoggedIn}">
		<table class="header_content_table">
			<tr>
				<td align="left" width="50px" style="text-align: right;">

					<div class="art-logo">
						<h:commandLink styleClass="logo" action="homePage">
							<p:graphicImage
								url="/resources/images/decoration/logo_header.png"
								style="height: 24px;" />
						</h:commandLink>
					</div>
				</td>
				<td align="right"><h:outputText
						style="position: relative;top: -5px;right: 10px;"
						rendered="#{loginBean.userLoggedIn and navigationBean.userGuest and navigationBean.guestRoomId ne null}"
						value="Room: #{navigationBean.roomName}">
					</h:outputText></td>
			</tr>
		</table>
		<!-- questo blocca l'interfaccia!!!  <ace:submitMonitor id="submitMonitor2" blockUI="@all" /> -->
		<p:notificationBar position="top"
			rendered="#{navigationTabsBean.showPopupMessages}"
			visible="#{navigationTabsBean.showPopupMessages}" effect="slide"
			styleClass="top" widgetVar="systemMessages">
			<h:panelGroup id="contenitore_monitors" layout="block"
				style="display:  table; width: 100%;">
				<ui:repeat var="mess" value="#{navigationTabsBean.messages}">

					<h:panelGroup layout="block" style="display:  table-row;">
						<h:panelGroup layout="block"
							style="display: table-cell; padding-left: 3px; vertical-align: top;">
							<h:graphicImage alt="#{mess.messageType}"
								title="#{mess.messageType}"
								url="/resources/images/alerts/big/#{mess.type}.gif" />
						</h:panelGroup>
						<h:panelGroup layout="block"
							style="display: table-cell; padding-left: 3px; vertical-align: top;">
							<h:outputText
								style="font-family: Verdana; font-size: 16px; left: 36px; position: relative;"
								value="#{mess.message}" />
						</h:panelGroup>
					</h:panelGroup>
				</ui:repeat>
			</h:panelGroup>
			<p:commandButton value="Hide" onclick="PF('systemMessages').hide()"
				type="button" icon="ui-icon-arrow-1-n" />
		</p:notificationBar>
		<p:growl globalOnly="false" for="@all" redisplay="false" life="7000" />
	</h:form>
</ui:composition>